--- #This is yaml file for ansible
- hosts: demo
  become: True
  connection: ssh
  tasks:
      - name: install apache
        yum: 
          name: "httpd" 
          state: "present"
          
             
             
      
        
        
        
