--- #This is yaml file for ansible
- hosts: demo
  become: yes
  user: root
  connection: ssh
  
  tasks:
      - name: install apache
        yum: name=httpd state=present
      - name: start apache server
        service:
             name=httpd 
             state=started 
             enabled=True
      - name: copy index.html
        copy: src= index.html dest: /var/www/html/
        
        
        
