--- #This is yaml file for ansible
- hosts: demo
  become: True
  connection: ssh
  tasks:
      - name: install apache
        yum: 
          name: "httpd" 
          state: "present"
      - name: start apache
        service:
          name: httpd
          state: started
          enabled: True
      - name: deploy index file
        copy:
           src: index.html 
          dest: /var/www/html
          
             
             
      
        
        
        
