--- #This is yaml file for ansible
- hosts: demo
  become: yes
  connection: ssh
  tasks:
      - name: install apache
        yum: name=httpd state=present
      - name: start apache server
        action: service name= httpd state=started 
      - name: copy index.html
        copy: src= index.html dest= /var/www/html/       
             
             
      
        
        
        
